springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  servlet:
    context-path: ${SWAGGER_URL}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}